# For detailed information about docker-compose visit https://docs.docker.com/compose/
# To start all docker containers required to execute the tests locally run:
# docker-compose up

version: '2.2'
services:
  gcloud-pubsub-emulator:
    image: google/cloud-sdk:311.0.0
    ports:
      - "8538:8538"
    command: gcloud beta emulators pubsub start --project=pekko-connectors --host-port=0.0.0.0:8538
  gcloud-pubsub-emulator_prep:
    image: martynas/gcloud-pubsub-client
    links:
      - "gcloud-pubsub-emulator"
    environment:
      - "PUBSUB_PROJECT_ID=pekko-connectors"
      - "PUBSUB_EMULATOR_HOST=gcloud-pubsub-emulator:8538"
    entrypoint: ""
    command: >
      bash -c "
        python publisher.py pekko-connectors create simpleTopic &&
        python subscriber.py pekko-connectors create simpleTopic simpleSubscription
        python publisher.py pekko-connectors create testTopic &&
        python subscriber.py pekko-connectors create testTopic testSubscription
      "
